### PR TITLE
add composer/installers allows changeing path where package installed

### PR DESCRIPTION
**Pull request by matgargano**

### CODE REVIEW

**Comment by matgargano** [comment]
@prettyboymp any way we can merge this in so i can specify where to install this, i can tag a new release after you merge

**Comment by kevinlangleyjr** [comment]
@matstars - Why is this needed to specify a different install path?

Why can't you just use installer-paths in your project? I can provide an example if one is needed...

**Comment by kevinlangleyjr** [comment]
Spoke too soon - looks like that does need to be added to be able to use the `installer-paths` in composer.

https://getcomposer.org/doc/faqs/how-do-i-install-a-package-to-a-custom-path-for-my-framework.md

**Comment by matgargano** [comment]
@kevinlangleyjr as I understand it, in order to use something along the lines of 

```
{

  ...

    "extra": {
        "installer-paths": {
            "wp-content/plugins/{$name}": [

                "voceconnect/wp-large-options"
            ]

        }

    }

  ...

}
```

the package, in this instance `voceconnect/wp-large-options` needs to require `composer/installers` otherwise it just installs it in the vendor directory (which I can override in my projects composer.json)

If I'm mistaken, let me know.

**Comment by kevinlangleyjr** [comment]
No, you are correct - but you are going to need to add the correct type per the link I posted above.

**Pull request merged**
